services:
  - type: static
    name: kodumunhatasi-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - source: /*
        destination: /index.html